### ISSUE TITLE
Request new release with rxjs 6+

### ISSUE THREAD

**Issue by hackeo1** [angular-slider/ngx-slider#156]
Hi, This is not really an issue but it would be awesome if a new version is released with an updated 	rxjs dependency, if there is any possibility for it

**Comment by Fattouh92** [comment]
this is actually an issue if your project does not have rxjs-compat explicitly installed when outputting sourcemaps and results in the following warning while building for prod

```
WARNING in ./node_modules/rxjs-compat/_esm2015/Subject.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/compat/Subject.ts': Error: Can't resolve '../src/compat/Subject.ts' in '/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/rxjs-compat/_esm2015'
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../src/compat/Subject.ts': Error: Can't resolve '../src/compat/Subject.ts' in '/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/rxjs-compat/_esm2015'
    at emitWarning (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/webpack/lib/NormalModule.js:159:16)
    at /Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/source-map-loader/index.js:80:7
    at doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn6 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:69:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at fs.stat (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
    at VirtualFileSystemDecorator.stat (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:32:13)
    at resolver.getHook.tapAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:18:7)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/TryNextPlugin.js:17:13)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
 @ ./node_modules/ng5-slider/esm2015/ng5-slider.js 1:0-39 553:30-37 599:30-37 977:43-50 979:44-51
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/rxjs-compat/_esm2015/Subscription.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/compat/Subscription.ts': Error: Can't resolve '../src/compat/Subscription.ts' in '/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/rxjs-compat/_esm2015'
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../src/compat/Subscription.ts': Error: Can't resolve '../src/compat/Subscription.ts' in '/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/rxjs-compat/_esm2015'
    at emitWarning (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/webpack/lib/NormalModule.js:159:16)
    at /Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/source-map-loader/index.js:80:7
    at doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn6 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:69:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at fs.stat (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
    at VirtualFileSystemDecorator.stat (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:32:13)
    at resolver.getHook.tapAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:18:7)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/TryNextPlugin.js:17:13)
    at _fn0 (eval at create (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)
    at hook.callAsync (/Users/mohamed/smec-dev/smec-shopping/shopping-ui/web-client/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
 @ ./node_modules/ng5-slider/esm2015/ng5-slider.js 2:0-27
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Comment by ruisilva450** [comment]
If this repo is all about the ng**5**-slider, we need another repo forked from this one and start the migration. 
On Angular 7/8 we shouldn't need to maintain rxjs < 6

**Comment by john-melin** [comment]
Using pre 6 rxjs like this is bananas. It requires the rxjs package to be duplicated in the project using it. Say you had 3 dependencies doing the same thing as ng5-slider, you would have 3 copys of rxjs in your project.

**Comment by merobal** [comment]
I just found this now via Google search: https://github.com/m0t0r/ngx-slider

**Comment by piotrdz** [comment]
v2.0 targeting Angular 6+ and rxjs 6+ is coming very soon.

**Comment by piotrdz** [comment]
v2.0.0 is now released. Closing.
